---
title: "Understanding Flow Triggers: Event vs. Batch Processing"
description: "Learn the foundational difference between Event and Batch triggers and how to apply them to initiate workflows based on single events or bulk data synchronization."
layout: tutorial_slide
tutorial_number: 2
steps:
  - step_number: 1
    step_title: "Welcome to Triggers"
    narrator_script: "Every single flow within Lamatic.ai must be initiated by a **Trigger Node**. This is the starting point that dictates when and how the workflow executes, whether it's an instantaneous reaction or a large-scale data sync.[1] Choosing the correct trigger type is the first critical architectural decision for any new GenAI application."
    on_screen_text:
      - "All Flows Require a Trigger Node"
      - "Defines Execution Timing and Input"
      - "First Critical Architectural Step"
    action_visual_cue: "Highlight the Trigger Node at the start of an empty flow editor."
  - step_number: 2
    step_title: "Defining the Event Trigger"
    narrator_script: "The **Event Trigger** is designed for instantaneous, one-time execution.[2] It fires when a singular, specific action or event occurs in an integrated application. Since it processes only one item, the flow runs just once per trigger, making it perfect for real-time responses and immediate interactions, such as a user message or an API call.[2]"
    on_screen_text:
      - "Initiated by a Single Event"
      - "Results in One-Time Execution"
      - "Ideal for Real-Time Responses"
    action_visual_cue: "Display an animation of a single message icon flowing into the Trigger Node, resulting in one execution path."
  - step_number: 3
    step_title: "Defining the Batch Trigger"
    narrator_script: "In contrast, the **Batch Trigger** is used for processing large collections of data inputs, or batches.[2] When a batch process is initiated, the flow executes multiple times—once for every item contained within the batch.[2] This trigger is essential for scenarios involving bulk synchronization, data transformation pipelines, or tasks requiring volume processing."
    on_screen_text:
      - "Triggered by Batch Processing"
      - "Executes Multiple Times"
      - "One Run Per Item in the Batch"
    action_visual_cue: "Display an animation of a stack of records flowing into the Trigger Node, resulting in multiple, distinct executions."
  - step_number: 4
    step_title: "Event Trigger in Practice (Slack Example)"
    narrator_script: "Consider a common Event Trigger use case: integrating with Slack.[2] A flow can be configured to start immediately when a new message is posted in a specific channel. The flow executes instantly to process that singular message, perhaps summarizing it using an AI Node, resulting in immediate, low-latency interaction.[2]"
    on_screen_text:
      - "Example: New Message in Slack"
      - "Flow Executes Instantly and Once"
      - "Used for Low-Latency Interaction"
    action_visual_cue: "Show the Slack App Node being configured as an Event Trigger in the flow configuration panel."
  - step_number: 5
    step_title: "Batch Trigger in Practice (PostgreSQL Example)"
    narrator_script: "The Batch Trigger is best demonstrated by database integration, such as synchronizing new records from a PostgreSQL database.[2] If the sync pulls 100 new records, the Batch Trigger ensures your flow runs 100 individual times, allowing you to apply logic or transformation to each record independently. This ensures reliable data pipeline operations.[2]"
    on_screen_text:
      - "Example: PostgreSQL Database Sync"
      - "Flow Runs Multiple Times (e.g., 100)"
      - "Used for ETL Data Pipelines"
    action_visual_cue: "Show the PostgreSQL App Node being configured as a Batch Trigger, with a notional batch size of 100 records."
  - step_number: 6
    step_title: "Connecting Triggers to Action Nodes"
    narrator_script: "The output generated by the Trigger Node must be passed sequentially to the next component, known as the **Action Node**.[1] Action nodes perform the actual work—like calling the Generate Text AI Node or connecting to an external API.[1] By chaining these nodes, you ensure the trigger's data output is correctly fed into the subsequent processing steps."
    on_screen_text:
      - "Trigger Output Feeds Action Nodes"
      - "Action Nodes Perform Core Processing"
      - "Maintain Sequential Logical Order"
    action_visual_cue: "Demonstrate dragging an output connection from the configured Trigger Node to a new, empty Action Node space."
  - step_number: 7
    step_title: "Concluding with the Final Node"
    narrator_script: "All successful flow executions should conclude with a **Final Node**.[1] This component is essential for formatting and sending the flow's ultimate output back to the initiating system, especially for requests that began with GraphQL or Chat Widget integrations.[1] This step closes the execution loop and delivers the result to the end-user or connected application."
    on_screen_text:
      - "Final Step of the Flow"
      - "Sends Output to External System"
      - "Completes API or Widget Request"
    action_visual_cue: "Show the final step connecting to a 'Final Node' icon, symbolizing the completion of data transmission."
  - step_number: 8
    step_title: "Tutorial Complete!"
    narrator_script: "You have now mastered the fundamental difference between Event and Batch triggers, providing you with the essential knowledge to architect complex, high-performance flows. You are now ready to proceed to the next tutorial to learn how to manage the Lamatic Studio interface and set up your projects."
    on_screen_text:
      - "Triggers Mastered"
      - "Event: One Time Execution"
      - "Batch: Multiple Executions"
      - "Next: Studio Navigation and Project Management"
    action_visual_cue: "Display an encouraging completion screen with a link or button to the next tutorial module."
---